/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DfsSlatePlayer } from './dfsSlatePlayer';
import { DfsSlateTournament } from './dfsSlateTournament';


export interface DfsSlate { 
    slateID?: number;
    operator?: string;
    operatorSlateID?: number;
    operatorName?: string;
    operatorDay?: string;
    operatorStartTime?: string;
    numberOfTournaments?: number;
    isMultiDaySlate?: boolean;
    removedByOperator?: boolean;
    operatorGameType?: string;
    dfsSlateTournaments?: Array<DfsSlateTournament>;
    dfsSlatePlayers?: Array<DfsSlatePlayer>;
    slateRosterSlots?: Array<string>;
}
