/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tournament } from './tournament';


export interface DfsSlateTournament { 
    slateTournamentID?: number;
    slateID?: number;
    tournamentID?: number;
    tournament?: Tournament;
    operatorTournamentID?: number;
    removedByOperator?: boolean;
}
