/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DfsSlatePlayer { 
    slatePlayerID?: number;
    slateID?: number;
    slateTournamentID?: number;
    playerID?: number;
    playerTournamentProjectionID?: number;
    operatorPlayerID?: string;
    operatorSlatePlayerID?: string;
    operatorPlayerName?: string;
    operatorPosition?: string;
    operatorSalary?: number;
    operatorRosterSlots?: Array<string>;
    removedByOperator?: boolean;
}
