/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface News { 
    newsID?: number;
    playerID?: number;
    title?: string;
    content?: string;
    url?: string;
    source?: string;
    termsOfUse?: string;
    updated?: string;
    author?: string;
    categories?: string;
    originalSource?: string;
    originalSourceUrl?: string;
}
