/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlayerHole { 
    playerRoundID?: number;
    number?: number;
    par?: number;
    score?: number;
    toPar?: number;
    holeInOne?: boolean;
    doubleEagle?: boolean;
    eagle?: boolean;
    birdie?: boolean;
    isPar?: boolean;
    bogey?: boolean;
    doubleBogey?: boolean;
    worseThanDoubleBogey?: boolean;
}
