/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlayerSeason { 
    playerSeasonID?: number;
    season?: number;
    playerID?: number;
    name?: string;
    worldGolfRank?: number;
    worldGolfRankLastWeek?: number;
    events?: number;
    averagePoints?: number;
    totalPoints?: number;
    pointsLost?: number;
    pointsGained?: number;
}
