/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Player { 
    playerID?: number;
    firstName?: string;
    lastName?: string;
    weight?: number;
    swings?: string;
    pgaDebut?: number;
    country?: string;
    birthDate?: string;
    birthCity?: string;
    birthState?: string;
    college?: string;
    photoUrl?: string;
    sportRadarPlayerID?: string;
    pgaTourPlayerID?: number;
    rotoworldPlayerID?: number;
    rotoWirePlayerID?: number;
    fantasyAlarmPlayerID?: number;
    draftKingsName?: string;
    fantasyDraftName?: string;
    fanDuelName?: string;
    fantasyDraftPlayerID?: number;
    draftKingsPlayerID?: number;
    fanDuelPlayerID?: number;
    yahooPlayerID?: number;
}
