/**
 * Golf v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Round } from './round';


export interface Tournament { 
    tournamentID?: number;
    name?: string;
    startDate?: string;
    endDate?: string;
    isOver?: boolean;
    isInProgress?: boolean;
    venue?: string;
    location?: string;
    par?: number;
    yards?: number;
    purse?: number;
    startDateTime?: string;
    canceled?: boolean;
    covered?: boolean;
    city?: string;
    state?: string;
    zipCode?: string;
    country?: string;
    timeZone?: string;
    format?: string;
    rounds?: Array<Round>;
    sportRadarTournamentID?: string;
}
